---
Name: metatags
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Arillo\MetaTags\MetaTagsExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Arillo\MetaTags\MetaTagsExtension
